// Generated by https://quicktype.io

export interface StandingsResponse {
    _internal: Internal;
    league:    League;
}

export interface Internal {
    pubDateTime:             string;
    igorPath:                string;
    xslt:                    string;
    xsltForceRecompile:      string;
    xsltInCache:             string;
    xsltCompileTimeMillis:   string;
    xsltTransformTimeMillis: string;
    consolidatedDomKey:      string;
    endToEndTimeMillis:      string;
}

export interface League {
    standard:   Standing;
    africa:     Standing;
    sacramento: Standing;
    vegas:      Standing;
    utah:       Standing;
}

export interface Standing {
    seasonYear:    number;
    seasonStageId: number;
    teams:         Team[];
}

export interface Team {
    teamId:                 string;
    win:                    string;
    loss:                   string;
    winPct:                 Pct;
    winPctV2:               string;
    lossPct:                Pct;
    lossPctV2:              string;
    gamesBehind:            string;
    divGamesBehind:         string;
    clinchedPlayoffsCode:   string;
    clinchedPlayoffsCodeV2: string;
    confRank:               string;
    confWin:                string;
    confLoss:               string;
    divWin:                 string;
    divLoss:                string;
    homeWin:                string;
    homeLoss:               string;
    awayWin:                string;
    awayLoss:               string;
    lastTenWin:             string;
    lastTenLoss:            string;
    streak:                 string;
    divRank:                string;
    isWinStreak:            boolean;
    teamSitesOnly:          TeamSitesOnly;
    tieBreakerPts:          string;
    sortKey:                { [key: string]: number };
}

export enum Pct {
    The000 = ".000",
    The1000 = "1.000",
    The200 = ".200",
    The333 = ".333",
    The400 = ".400",
    The600 = ".600",
    The667 = ".667",
    The800 = ".800",
}

export interface TeamSitesOnly {
    teamKey:            string;
    teamName:           string;
    teamCode:           string;
    teamNickname:       string;
    teamTricode:        string;
    clinchedConference: string;
    clinchedDivision:   string;
    clinchedPlayoffs:   string;
    streakText:         StreakText;
}

export enum StreakText {
    Empty = "-",
}
